export const Projects = [
    {
        name: 'Trunfo',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Front-end',
        tolls: ['React', 'Javascript'],
        git: 'KKKK',
    },
    {
        name: 'Trybetunes',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Front-end',
        tolls: ['React', 'Javascript'],
        git: 'KKKK',
    },
    {
        name: 'Frontend Online Store',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Front-end',
        tolls: ['React', 'Javascript'],
        git: 'KKKK',
    },
    {
        name: 'React testing library',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Front-end',
        tolls: ['React', 'Javascript', 'RTL'],
        git: 'KKKK',
    },
    {
        name: 'Wallet',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Front-end',
        tolls: ['React', 'Javascript', 'Redux'],
        git: 'KKKK',
    },
    {
        name: 'Star wars',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Front-end',
        tolls: ['React', 'Javascript'],
        git: 'KKKK',
    },
    {
        name: 'Recepies App',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Front-end',
        tolls: ['React', 'Javascript'],
        git: 'KKKK',
    },
    {
        name: 'Docker To Do List',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Docker'],
        git: 'KKKK',
    },
    {
        name: 'MySQL All For One',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['MySQL'],
        git: 'KKKK',
    },
    {
        name: 'MySQL One For All',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['MySQL'],
        git: 'KKKK',
    },
    {
        name: 'Talker Manager',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Node.js', 'Express', 'Javascript', 'Docker' , 'MySQL'],
        git: 'KKKK',
    },
    {
        name: 'Store Manager',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Node.js', 'Express', 'Javascript', 'Docker' , 'MySQL'],
        git: 'KKKK',
    },
    {
        name: 'Blogs API',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Node.js', 'Express', 'Javascript', 'Docker' , 'MySQL', 'Sequelize'],
        git: 'KKKK',
    },
    {
        name: 'Heroku - Backend',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Heroku', 'Javascript', 'Node.js'],
        git: 'KKKK',
    },
    {
        name: 'Heroku - Frontend',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Heroku', 'Javascript', 'Node.js'],
        git: 'KKKK',
    },
    {
        name: 'Trybesmith',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Node.js', 'Typescript'],
        git: 'KKKK',
    },
    {
        name: 'Trybers and Dragons',
        img: 'img',
        description: 'OPP',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Node.js', 'Typescript'],
        git: 'KKKK',
    },
    {
        name: 'Trybe Futebol Club',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Node.js', 'Express', 'Typescript', 'Docker' , 'MySQL', 'Sequelize', 'React'],
        git: 'KKKK',
    },
    {
        name: 'Commerce',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Node.js', 'Javascript', 'MongoDb'],
        git: 'KKKK',
    },
    {
        name: 'Car Shop',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Node.js', 'Typescript', 'Express.js', 'MongoDb', 'Mongoose'],
        git: 'KKKK',
    },
    {
        name: 'Jobs insights',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Python'],
        git: 'KKKK',
    },
    {
        name: 'Inventory report',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Python'],
        git: 'KKKK',
    },
    {
        name: 'Tech News',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Python'],
        git: 'KKKK',
    },
    {
        name: 'Algorithms',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Python'],
        git: 'KKKK',
    },
    {
        name: 'Trybe is not Google',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Python'],
        git: 'KKKK',
    },
    {
        name: 'Restaurant Orders',
        img: 'img',
        description: 'xxxxxxxxxxxxxxxxxxxxxxx',
        url: 'url.******',
        category: 'Back-end',
        tolls: ['Python'],
        git: 'KKKK',
    },
    
];

export const stacks = [
    { value: 'Javascript', label: 'Javascript' },
    { value: 'React', label: 'React' },
    { value: 'Node.js', label: 'Node.js' },
    { value: 'Python', label: 'Python' },
    { value: 'Typescript', label: 'Typescript' },
    { value: 'Docker', label: 'Docker' },
    { value: 'MySQL', label: 'MySQL' },
    { value: 'MongoDb', label: 'MongoDb' },
    { value: 'Sequelize', label: 'Sequelize' },
    { value: 'Mongoose', label: 'Mongoose' },
    { value: 'Jest', label: 'Jest' },
    { value: 'RTL', label: 'RTL' },
    { value: 'Express.js', label: 'Express.js' },
    { value: 'Heroku', label: 'Heroku' }
];

export const categories = [
    { value: 'Todas', label: 'Todas' },
    { value: 'Back-end', label: 'Back-end' },
    { value: 'Front-end', label: 'Front-end' }
];

